# Generated by Django 4.2.16 on 2025-10-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_phase2_core'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='couponredemption',
            new_name='store_coupo_redeeme_df13fa_idx',
            old_name='store_coupon_redemptions_redeemed_at_idx',
        ),
    ]
