# Generated by Django 4.2.16 on 2025-10-09 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def promote_roles(apps, schema_editor):
    User = apps.get_model('store', 'User')
    User.objects.filter(role='supplier').update(role='vendor')
    User.objects.filter(is_superuser=True).update(role='admin')
    User.objects.filter(is_staff=True).exclude(role__in=['admin', 'staff']).update(role='staff')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_seed_shop_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('customer', 'Customer'), ('vendor', 'Vendor')], default='customer', max_length=16),
        ),
        migrations.RunPython(promote_roles, reverse_code=noop_reverse),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=120)),
                ('object_pk', models.CharField(blank=True, max_length=64)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource', 'action'], name='store_admin_resourc_cf647b_idx'), models.Index(fields=['created_at'], name='store_admin_created_c768fa_idx')],
            },
        ),
    ]
